version: '3.8'

services:
  web:
    image: repivot:latest
    ports:
      - "8388:8000"
    volumes:
      - ./revolut.db:/app/revolut.db
      - ./static/icon.svg:/app/static/icon.svg
    env_file:
      - .env
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
